#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend alogyn.tech_backend

backend alogyn.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 511631-web-01 54.90.11.224:80 check
    server 511631-web-02 100.25.157.67:80 check
EOT

sudo service haproxy restart
