#!/usr/bin/env bash
# Script to ping an IP address 5 times

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS="$1"

ping -c 5 "$IP_ADDRESS"
