#!/usr/bin/env bash

# Write the PID of this script to /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

# Function to remove PID file and exit
cleanup() {
    rm /var/run/myscript.pid
    exit
}

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
    # Trap SIGTERM and SIGINT signals and define custom behavior
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && cleanup' SIGTERM
    trap 'cleanup' SIGQUIT
done
