#!/usr/bin/env bash
# This script gives information about the "school" file

file_name="school"

# Check if the file exists
if [ -e "$file_name" ]; then
    echo "$file_name file exists"

    # Check if the file is empty or not
    if [ -s "$file_name" ]; then
        echo "$file_name file is not empty"
    else
        echo "$file_name file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$file_name" ]; then
        echo "$file_name is a regular file"
    fi
else
    echo "$file_name file does not exist"
fi
