#!/usr/bin/env bash
# Restarts Gunicorn

# Find the Gunicorn master process ID
gunicorn_master_pid=$(pgrep -f 'gunicorn.*master')

if [ -z "$gunicorn_master_pid" ]; then
    echo "No Gunicorn master process found."
    exit 1
fi

# Stop Gunicorn master process
echo "Stopping Gunicorn master process (PID: $gunicorn_master_pid)..."
kill -QUIT "$gunicorn_master_pid"

# Wait for a few seconds to ensure Gunicorn has stopped
sleep 2

# Start Gunicorn again
echo "Starting Gunicorn..."
gunicorn --bind 0.0.0.0:8001 --workers 4 web_flask.0-hello_route:app &

echo "Gunicorn restarted successfully"
